FROM tensorflow/tensorflow

EXPOSE 80

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install --no-cache-dir --upgrade -r requirements.txt

WORKDIR /app

COPY . /app

CMD ["uvicorn", "pyapp.main:app", "--host", "0.0.0.0", "--port", "80", "--log-level", "critical"]